### ISSUE TITLE
Add "bacon" tag?

### ISSUE THREAD

**Issue by ggnkua** [LunaGao/BlessYourCodeTag#2]
Hi, would you consider adding a "bacon" tag like the one attached?

[bacon.zip](https://github.com/LunaGao/BlessYourCodeTag/files/1501646/bacon.zip)

**Comment by LunaGao** [comment]
As you wish :)

**Comment by LunaGao** [comment]
resolved #4. Thank you, ggnkua.

**Comment by LunaGao** [comment]
resolved #4
